// Shared layout definitions drive the picker, design preview and real app.
const rows = (...lines) => lines.map((line) => line.split(" "));
/** @type {Array<[string, string, string, string, string[][], number, "list"|"cards"|"timeline"|"compact"]>} */
const definitions = [
  [
    "dashboard",
    "Classic dashboard",
    "Dashboards",
    "Metrics above a broad work list and action panel.",
    rows(
      "heading heading heading",
      "widgets widgets widgets",
      "stats stats stats",
      "recent recent actions",
    ),
    3,
    "list",
  ],
  [
    "focus",
    "Focus desk",
    "Workspaces",
    "A centered work-first page with summaries below.",
    rows(
      "heading heading",
      "recent recent",
      "actions actions",
      "widgets widgets",
      "stats stats",
    ),
    2,
    "list",
  ],
  [
    "split",
    "Split workspace",
    "Workspaces",
    "A metrics column beside recent work and next actions.",
    rows("heading heading", "widgets recent", "widgets actions", "stats stats"),
    1,
    "list",
  ],
  [
    "wide",
    "Wide overview",
    "Dashboards",
    "A panoramic metrics band above a wide work area.",
    rows(
      "heading heading heading heading",
      "widgets widgets widgets widgets",
      "stats stats stats stats",
      "recent recent recent actions",
    ),
    4,
    "compact",
  ],
  [
    "scoreboard",
    "Scoreboard",
    "Analytics",
    "Summary strip with a tall work rail beside the analysis.",
    rows(
      "heading heading heading",
      "stats stats stats",
      "widgets widgets recent",
      "actions actions recent",
    ),
    2,
    "compact",
  ],
  [
    "pulse",
    "Pulse monitor",
    "Analytics",
    "Actions stay alongside the introduction and summary.",
    rows(
      "heading heading actions",
      "stats stats actions",
      "widgets widgets recent",
    ),
    2,
    "list",
  ],
  [
    "metric-wall",
    "Metric wall",
    "Analytics",
    "A wall of metrics with three supporting panels below.",
    rows(
      "heading heading heading",
      "widgets widgets widgets",
      "stats recent actions",
    ),
    3,
    "cards",
  ],
  [
    "insights-rail",
    "Insights rail",
    "Analytics",
    "A vertical summary rail alongside data and work.",
    rows(
      "heading heading heading",
      "widgets widgets stats",
      "recent actions stats",
    ),
    2,
    "compact",
  ],
  [
    "report-desk",
    "Report desk",
    "Analytics",
    "A persistent metric column beside summaries and records.",
    rows(
      "heading heading",
      "stats widgets",
      "recent widgets",
      "actions actions",
    ),
    1,
    "timeline",
  ],
  [
    "executive",
    "Executive brief",
    "Analytics",
    "A full introduction followed by summary, work and analysis columns.",
    rows(
      "heading heading heading",
      "stats recent widgets",
      "actions recent widgets",
    ),
    1,
    "list",
  ],
  [
    "comparison",
    "Comparison desk",
    "Analytics",
    "Balanced analysis and summary panels above a work strip.",
    rows(
      "heading heading",
      "widgets stats",
      "actions actions",
      "recent recent",
    ),
    2,
    "cards",
  ],
  [
    "signal",
    "Signal board",
    "Analytics",
    "A leading work column with stacked summary and actions.",
    rows(
      "heading heading heading",
      "recent recent stats",
      "recent recent actions",
      "widgets widgets widgets",
    ),
    3,
    "timeline",
  ],
  [
    "inbox",
    "Inbox workspace",
    "Workspaces",
    "A full-height work queue beside compact tools.",
    rows(
      "heading heading heading",
      "recent recent widgets",
      "recent recent stats",
      "recent recent actions",
    ),
    1,
    "compact",
  ],
  [
    "command",
    "Command desk",
    "Workspaces",
    "Three equally weighted operational columns.",
    rows(
      "heading heading heading",
      "widgets recent stats",
      "widgets recent actions",
    ),
    1,
    "cards",
  ],
  [
    "workbench",
    "Workbench",
    "Workspaces",
    "A broad work surface between top and bottom information bands.",
    rows(
      "heading heading heading",
      "stats stats stats",
      "recent recent actions",
      "widgets widgets widgets",
    ),
    3,
    "cards",
  ],
  [
    "queue",
    "Queue and context",
    "Workspaces",
    "A compact queue at left with a larger context area.",
    rows(
      "heading heading heading",
      "recent widgets widgets",
      "recent stats stats",
      "actions actions actions",
    ),
    3,
    "compact",
  ],
  [
    "review",
    "Review station",
    "Workspaces",
    "A work column flanked by summary and action rails.",
    rows(
      "heading heading heading",
      "stats recent actions",
      "widgets recent actions",
    ),
    1,
    "timeline",
  ],
  [
    "task-focus",
    "Task focus",
    "Workspaces",
    "A narrow reading column, with metrics placed last.",
    rows("heading", "stats", "recent", "actions", "widgets"),
    1,
    "compact",
  ],
  [
    "journal",
    "Workspace journal",
    "Editorial",
    "A reading-first page with an opening summary sidebar.",
    rows(
      "heading heading stats",
      "recent recent stats",
      "widgets actions actions",
    ),
    1,
    "timeline",
  ],
  [
    "magazine",
    "Magazine desk",
    "Editorial",
    "A broad opening and a feature panel beside supporting columns.",
    rows(
      "heading heading heading",
      "actions actions stats",
      "recent widgets widgets",
    ),
    2,
    "cards",
  ],
  [
    "feature",
    "Feature story",
    "Editorial",
    "An oversized action feature anchors the left half.",
    rows(
      "heading heading",
      "actions widgets",
      "actions stats",
      "recent recent",
    ),
    2,
    "list",
  ],
  [
    "digest",
    "Daily digest",
    "Editorial",
    "Short summaries precede a full-width chronological work list.",
    rows(
      "heading heading heading",
      "stats widgets actions",
      "recent recent recent",
    ),
    1,
    "timeline",
  ],
  [
    "briefing",
    "Morning briefing",
    "Editorial",
    "Introduction and highlights share the opening band.",
    rows(
      "heading heading actions",
      "widgets stats stats",
      "recent recent recent",
    ),
    1,
    "list",
  ],
  [
    "notebook",
    "Notebook",
    "Editorial",
    "A centered long-form layout with a side note column.",
    rows(
      "heading heading",
      "recent actions",
      "recent stats",
      "widgets widgets",
    ),
    2,
    "timeline",
  ],
  [
    "editorial-grid",
    "Editorial grid",
    "Editorial",
    "Work and supporting panels form an asymmetric grid.",
    rows(
      "heading heading heading",
      "recent widgets widgets",
      "stats stats actions",
    ),
    3,
    "cards",
  ],
  [
    "reading-room",
    "Reading room",
    "Editorial",
    "A full-width work stream opens before metrics and highlights.",
    rows(
      "heading heading",
      "recent recent",
      "stats actions",
      "widgets widgets",
    ),
    2,
    "list",
  ],
  [
    "welcome",
    "Welcome portal",
    "Portals",
    "An action panel shares the masthead above a work and data split.",
    rows("heading actions", "stats stats", "recent widgets"),
    2,
    "cards",
  ],
  [
    "client-home",
    "Client home",
    "Portals",
    "Project work leads, with two supporting rows of information.",
    rows(
      "heading heading heading",
      "recent recent recent",
      "widgets widgets actions",
      "stats stats actions",
    ),
    3,
    "cards",
  ],
  [
    "service-hub",
    "Service hub",
    "Portals",
    "Actions lead into a work list with a metric rail.",
    rows(
      "heading heading heading",
      "actions actions widgets",
      "recent recent widgets",
      "stats stats stats",
    ),
    1,
    "list",
  ],
  [
    "member-space",
    "Member space",
    "Portals",
    "A narrow work rail beside an expansive member overview.",
    rows(
      "heading heading heading",
      "recent widgets widgets",
      "recent actions actions",
      "stats stats stats",
    ),
    3,
    "list",
  ],
  [
    "project-hub",
    "Project hub",
    "Portals",
    "A large project area with a summary and metrics column.",
    rows(
      "heading heading heading",
      "recent recent stats",
      "recent recent widgets",
      "actions actions actions",
    ),
    1,
    "cards",
  ],
  [
    "concierge",
    "Concierge",
    "Portals",
    "An action rail accompanies a compact sequential overview.",
    rows(
      "heading heading actions",
      "recent recent actions",
      "widgets stats stats",
    ),
    1,
    "compact",
  ],
];
const tabletPatterns = {
  list: rows(
    "heading heading",
    "widgets widgets",
    "stats stats",
    "recent actions",
  ),
  cards: rows(
    "heading heading",
    "stats stats",
    "recent recent",
    "widgets actions",
  ),
  timeline: rows(
    "heading heading",
    "recent actions",
    "recent stats",
    "widgets widgets",
  ),
  compact: rows(
    "heading heading",
    "recent recent",
    "stats actions",
    "widgets widgets",
  ),
};
export const layoutPresets = definitions.map(
  ([id, name, category, description, desktop, widgetColumns, recordView]) => ({
    id,
    name,
    category,
    description,
    desktop,
    tablet: tabletPatterns[recordView],
    mobile: [...new Set(desktop.flat())],
    maxWidth:
      id === "wide"
        ? 1800
        : ["focus", "task-focus", "notebook", "reading-room"].includes(id)
          ? 1000
          : 1440,
    widgetColumns,
    recordView,
  }),
);
export const layoutIds = layoutPresets.map((p) => p.id);
export function getLayoutPreset(id = "dashboard") {
  const preset = layoutPresets.find((p) => p.id === id);
  if (!preset) throw new Error("Unknown app layout.");
  return preset;
}
